name: electroshare
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  file_picker: ^8.0.0
  cloud_firestore: ^5.6.7
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  http: ^1.1.0
  geolocator: ^14.0.0
  table_calendar: ^3.1.3
  intl: ^0.19.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
